FROM golang:1.10-stretch
MAINTAINER Yifan Wang <heavenstar@gmail.com>

# Download and install ipfs and clean up
RUN wget https://dist.ipfs.io/go-ipfs/v0.4.16/go-ipfs_v0.4.16_linux-amd64.tar.gz \
    && tar -xzf go-ipfs_v0.4.16_linux-amd64.tar.gz && cd go-ipfs && ./install.sh \
    && cd .. && rm go-ipfs_v0.4.16_linux-amd64.tar.gz && rm -r go-ipfs

# install redis, to start /etc/init.d/redis-server start
RUN apt-get update && apt-get upgrade -y && apt-get install redis-server -y \
    && grep -v "#" /etc/redis/redis.conf | grep -v -e '^$' | grep -v "^dir " > /etc/redis/redis.conf.2 \
    && mkdir -p /data/redis \
    && chown redis /data/redis \
    && chgrp redis /data/redis \
    && echo "dir /data/redis" >> /etc/redis/redis.conf.2 \
    && mv /etc/redis/redis.conf.2 /etc/redis/redis.conf \
    && go get -u gopkg.in/resty.v1 \
    && go get -u github.com/op/go-logging \
    && go get -u github.com/go-redis/redis \
    && go get -u github.com/prashantv/gostub \
    && go get -u github.com/smartystreets/goconvey/convey \
    && go get -u gopkg.in/validator.v2

RUN apt-get install lsof -y && apt-get install net-tools -y && apt-get install curl -y

# copy test files
COPY addins/ipfs/docker/start_server_test_env.sh /usr/local/sbin/
COPY addins/ipfs/monkey /ipfs_monkey

# make the sh file excutable
RUN chmod +x /usr/local/sbin/start_server_test_env.sh

# setup /data directory
RUN mkdir -p /data/ipfs

# setup ipfs data dir
ENV IPFS_PATH=/data/ipfs

# expose port
# ipfs
EXPOSE 4001
EXPOSE 4002/udp
EXPOSE 5001
EXPOSE 8080
EXPOSE 8081
# monkey
EXPOSE 18080

CMD ["start_server_test_env.sh"]
